export declare namespace UniPay {
  interface BScanCUniPayInfo {
    // 实际支付金额
    amount: string;
    // 自定义订单状态
    bizStatus: string;
    // 设备类型.
    deviceType: string;
    // 商品息json字符串
    goods: string;
    // 主键
    id: string;
    // 商户号
    merchantCode: string;
    // 业务订单号: 实际支付订单号
    merchantOrderId: string;
    // 商户备注
    merchantRemark: string;
    // 返回订单ID
    orderId: string;
    // 业务生成订单号
    orderNo: string;
    // 支付授权码
    payCode: string;
    // 支付方式
    payMode: string;
    // 结算参考号
    retrievalRefNum: string;
    // 结算日期
    settlementDateWithYear: string;
    // 请求系统预留字段
    srcReserve: string;
    // 终端号
    terminalCode: string;
    // 第三方支付者名称
    thirdPartyBuyerUserName: string;
    // 第三方优惠说明
    thirdPartyDiscountInstruction: string;
    // 第三方名称
    thirdPartyName: string;
    // 第三方订单号
    thirdPartyOrderId: string;
    // 第三方支付信息
    thirdPartyPayInformation: number;
    // 支付总金额
    transactionAmount: string;
    // 币种
    transactionCurrencyCode: string;
    // 交易日期
    transactionDateWithYear: string;
    // 交易时间.
    transactionTime: string;
  }

  interface CScanBUniPayInfo {
    // 应用ID
    appId: string;
    // 是否异步确认分账
    asynDivisionFlag: string;
    // 银行卡号信息
    bankCardNo: string;
    // 银行信息
    bankInfo: string;
    // 账单日期
    billDate: string;
    // 账单描述
    billDesc: string;
    // 账单号
    billNo: string;
    // 账单业务类型
    billPaymentBizType: string;
    // 买家ID
    billPaymentBuyerId: string;
    // 实付金额
    billPaymentBuyerPayAmount: number;
    // 买家用户名
    billPaymentBuyerUsername: string;
    // 渠道优惠金额
    billPaymentCouponAmount: number;
    // 联盟折扣金额
    billPaymentDiscountAmount: number;
    // 开票金额
    billPaymentInvoiceAmount: number;
    // 商户订单号
    billPaymentMerOrderId: string;
    // 支付详情
    billPaymentPayDetail: string;
    // 交易参考号
    billPaymentPaySeqId: string;
    // 支付时间
    billPaymentPayTime: string;
    // 实收金额
    billPaymentReceiptAmount: number;
    // 结算时间
    billPaymentSettleDate: string;
    // 交易状态
    billPaymentStatus: string;
    // 目标平台单号
    billPaymentTargetOrderId: string;
    // 目标系统
    billPaymentTargetSys: string;
    // 账单流水总金额
    billPaymentTotalAmount: number;
    // 账单状态
    billStatus: string;
    // 自定义订单状态
    bizStatus: string;
    // 实名认证证件号
    certNo: string;
    // 实名认证证件类型
    certType: string;
    // 桌号、柜台号、房间号
    counterNo: string;
    // 商户出资优惠金额
    couponMerchantContribute: number;
    // 其他优惠金额
    couponOtherContribute: number;
    // 分账标记
    divisionFlag: string;
    // 账单过期时间
    expireTime: string;
    // 是否需要实名认证
    fixBuyer: string;
    // 商品信息json字符串
    goods: string;
    // 主键
    id: string;
    // 业务类型
    instMid: string;
    // 是否需要限制信用卡支付
    limitCreditCard: string;
    // 会员号
    memberId: string;
    // 商户号
    mid: string;
    // 实名认证手机号
    mobile: string;
    // 消息ID
    msgId: string;
    // 实名认证姓名
    name: string;
    // 支付结果通知地址
    notifyUrl: string;
    // 业务订单号
    orderNo: string;
    // 平台商户分账金额
    platformAmount: number;
    // 二维码ID
    qrCodeId: string;
    // 实付金额
    receiptAmount: number;
    // 报文请求时间，格式yyy-MM-ddHH:mm:ss
    requestTimestamp: string;
    // 网页跳转地址
    returnUrl: string;
    // 担保交易标识
    secureTransaction: string;
    // 请求系统预留字段
    srcReserve: string;
    // 子订单信息
    subOrders: string;
    // 系统ID
    systemId: string;
    // 终端号
    tic: string;
    // 支付总金额
    totalAmount: number;
    // 钱包选项
    walletOption: string;
  }
}
