type EnterpriseItem = {
  accountType: string;
  addressDetail: string;
  auditDesc: string;
  clientId: string;
  contactsEmail: string;
  contactsImgUrl: string;
  contactsName: string;
  contactsPhone: string;
  createDate: string;
  createName: string;
  enterpriseAddress: string;
  enterpriseName: string;
  id: string;
  isLock: string;
  licenseImgUrl: string;
  licenseNo: string;
  logo: string;
  source: string;
  status: string;
  submitTime: string;
  updateDate: string;
  updateName: string;
  userId: string;
  venueName: string;
  versions: number;
};
