export const questionCategory = {
  YESNO: '是非题',
  RADIO: '单选题',
  CHECKBOX: '多选题',
  FILLBLANK: '填空题',
  MULTIFILLBLANK: '多项填空题',
  ANSWER: '多行填空题',
  BIGQU: '大题',
  ENUMQU: '枚举题',
  SCORE: '评分题',
  ORDERQU: '排序题',
  PROPORTION: '比重题',
  CHENRADIO: '矩阵单选题',
  CHENFBK: '矩阵填空题',
  CHENCHECKBOX: '矩阵多选题',
  // 'COMPCHENRADIO': '复合矩阵单选题',
  UPLOADFILE: '文件上传题',
  PAGETAG: '分页标记',
  PARAGRAPH: '段落说明',
  CHENSCORE: '矩阵评分题',
  COMPRADIO: '复合单选',
  COMPCHECKBOX: '复合多选',
  SCALE: '量表题',
  // 'CHENSCALE': '矩阵量表题',
  MULTISLIDER: '多项滑块题',
  IMGRADIO: '图片单选题',
  IMGCHECKBOX: '图片多选题',
  SLIDER: '滑块题',
  CASCADE: '级联题',
};
